[phases.setup]
nixPkgs = ['nodejs', 'python3', 'gcc', 'vips']

[phases.install]
cmds = [
    'npm install -g node-gyp',
    'npm install --legacy-peer-deps'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'

[build.env]
NODE_ENV = "production"